// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  //new credentials sbi changes
  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAXm86ZOFmU6wdiU2OHS8wyxi7Rf1WIbVI",
  authDomain: "voizer-6fa3c.firebaseapp.com",
  databaseURL: "https://voizer-6fa3c-default-rtdb.firebaseio.com",
  projectId: "voizer-6fa3c",
  storageBucket: "voizer-6fa3c.firebasestorage.app",
  messagingSenderId: "708006854850",
  appId: "1:708006854850:web:bd965d767c5cde0205bb5b",
  measurementId: "G-L58XYLG3ET"

  );

  //old credentials
  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyAA23tOY5VWbArGTRWBicJaXq3ZlTMr928',
  //   appId: '1:1056180385787:android:032e12693c87ac06ca7d5e',
  //   messagingSenderId: '1056180385787',
  //   projectId: 'blue-vj',
  //   databaseURL: 'https://blue-vj-default-rtdb.firebaseio.com',
  //   storageBucket: 'blue-vj.firebasestorage.app',
  // );

  //new credentials sbi changes
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH2mjcQZptI63OzntaW0qzhgy9vAwedLo',
    appId: '1:708006854850:android:b12bf072403e1ff905bb5b',
    messagingSenderId: '708006854850',
    projectId: 'voizer-6fa3c',
    databaseURL: 'https://voizer-6fa3c-default-rtdb.firebaseio.com',
    storageBucket: 'voizer-6fa3c.firebasestorage.app',
  );

  //old credentials
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvDmRZdGi3u0rc5YkzFgzCym_oZkDxyMk',
    appId: '1:658280273501:ios:2a17ccc533d111d1919fb4',
    messagingSenderId: '658280273501',
    projectId: 'gamex-vj',
    databaseURL: 'https://gamex-vj-default-rtdb.firebaseio.com',
    storageBucket: 'gamex-vj.appspot.com',
    iosBundleId: 'gamex.voicejet.app',
  );

  //old credentials
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo0Sp7oVrEq2KJ5Lvs_P1O-YVLOVuCeQ4',
    appId: '1:332946405306:ios:ef47839c5a7d81d531cf83',
    messagingSenderId: '332946405306',
    projectId: 'voice-jet-admin',
    databaseURL: 'https://voice-jet-admin-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'voice-jet-admin.appspot.com',
    iosBundleId: 'com.example.agoraCallingAdmin.RunnerTests',
  );
}
